# Generated by Django 6.0.6 on 2026-07-09 04:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('games_text', models.CharField(max_length=400)),
                ('games_comment_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_user', to=settings.AUTH_USER_MODEL)),
                ('games_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_comments', to='Backend.games')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GamesRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Backend.games')),
                ('rating_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('game', 'rating_writer')},
            },
        ),
    ]
