# Generated by Django 6.0.6 on 2026-08-13 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0002_gamescomment_gamesrating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name_ru", models.CharField(max_length=120, verbose_name="Имя (RU)")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Имя (EN)"
                    ),
                ),
                (
                    "role_ru",
                    models.CharField(max_length=200, verbose_name="Должность (RU)"),
                ),
                (
                    "role_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Должность (EN)"
                    ),
                ),
                (
                    "tagline_ru",
                    models.TextField(blank=True, verbose_name="Короткое описание (RU)"),
                ),
                (
                    "tagline_en",
                    models.TextField(blank=True, verbose_name="Короткое описание (EN)"),
                ),
                (
                    "about_ru",
                    models.TextField(
                        blank=True,
                        help_text="Каждый абзац — с новой строки. Пустые строки игнорируются.",
                        verbose_name="Обо мне (RU)",
                    ),
                ),
                ("about_en", models.TextField(blank=True, verbose_name="Обо мне (EN)")),
                (
                    "cta_title_ru",
                    models.CharField(
                        blank=True,
                        default="Открыт к работе",
                        max_length=120,
                        verbose_name="CTA: заголовок (RU)",
                    ),
                ),
                (
                    "cta_title_en",
                    models.CharField(
                        blank=True,
                        default="Open to work",
                        max_length=120,
                        verbose_name="CTA: заголовок (EN)",
                    ),
                ),
                (
                    "cta_text_ru",
                    models.TextField(blank=True, verbose_name="CTA: текст (RU)"),
                ),
                (
                    "cta_text_en",
                    models.TextField(blank=True, verbose_name="CTA: текст (EN)"),
                ),
                (
                    "cta_btn1_text_ru",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        verbose_name="CTA: кнопка 1, текст (RU)",
                    ),
                ),
                (
                    "cta_btn1_text_en",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        verbose_name="CTA: кнопка 1, текст (EN)",
                    ),
                ),
                (
                    "cta_btn1_url",
                    models.URLField(
                        blank=True, max_length=300, verbose_name="CTA: кнопка 1, ссылка"
                    ),
                ),
                (
                    "cta_btn2_text_ru",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        verbose_name="CTA: кнопка 2, текст (RU)",
                    ),
                ),
                (
                    "cta_btn2_text_en",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        verbose_name="CTA: кнопка 2, текст (EN)",
                    ),
                ),
                (
                    "cta_btn2_url",
                    models.URLField(
                        blank=True, max_length=300, verbose_name="CTA: кнопка 2, ссылка"
                    ),
                ),
                (
                    "eyebrow_ru",
                    models.CharField(
                        blank=True,
                        default="Резюме",
                        max_length=60,
                        verbose_name="Ярлык над именем (RU)",
                    ),
                ),
                (
                    "eyebrow_en",
                    models.CharField(
                        blank=True,
                        default="Résumé",
                        max_length=60,
                        verbose_name="Ярлык над именем (EN)",
                    ),
                ),
                (
                    "contacts_title_ru",
                    models.CharField(
                        blank=True,
                        default="Контакты",
                        max_length=60,
                        verbose_name="Заголовок «Контакты» (RU)",
                    ),
                ),
                (
                    "contacts_title_en",
                    models.CharField(
                        blank=True,
                        default="Contacts",
                        max_length=60,
                        verbose_name="Заголовок «Контакты» (EN)",
                    ),
                ),
                (
                    "facts_title_ru",
                    models.CharField(
                        blank=True,
                        default="Коротко",
                        max_length=60,
                        verbose_name="Заголовок «Коротко» (RU)",
                    ),
                ),
                (
                    "facts_title_en",
                    models.CharField(
                        blank=True,
                        default="At a glance",
                        max_length=60,
                        verbose_name="Заголовок «Коротко» (EN)",
                    ),
                ),
                (
                    "about_title_ru",
                    models.CharField(
                        blank=True,
                        default="Обо мне",
                        max_length=60,
                        verbose_name="Заголовок «Обо мне» (RU)",
                    ),
                ),
                (
                    "about_title_en",
                    models.CharField(
                        blank=True,
                        default="About me",
                        max_length=60,
                        verbose_name="Заголовок «Обо мне» (EN)",
                    ),
                ),
                (
                    "stack_title_ru",
                    models.CharField(
                        blank=True,
                        default="Технический стек",
                        max_length=60,
                        verbose_name="Заголовок «Стек» (RU)",
                    ),
                ),
                (
                    "stack_title_en",
                    models.CharField(
                        blank=True,
                        default="Tech stack",
                        max_length=60,
                        verbose_name="Заголовок «Стек» (EN)",
                    ),
                ),
                (
                    "exp_title_ru",
                    models.CharField(
                        blank=True,
                        default="Опыт работы",
                        max_length=60,
                        verbose_name="Заголовок «Опыт» (RU)",
                    ),
                ),
                (
                    "exp_title_en",
                    models.CharField(
                        blank=True,
                        default="Experience",
                        max_length=60,
                        verbose_name="Заголовок «Опыт» (EN)",
                    ),
                ),
                (
                    "proj_title_ru",
                    models.CharField(
                        blank=True,
                        default="Проекты",
                        max_length=60,
                        verbose_name="Заголовок «Проекты» (RU)",
                    ),
                ),
                (
                    "proj_title_en",
                    models.CharField(
                        blank=True,
                        default="Projects",
                        max_length=60,
                        verbose_name="Заголовок «Проекты» (EN)",
                    ),
                ),
                (
                    "edu_title_ru",
                    models.CharField(
                        blank=True,
                        default="Образование",
                        max_length=60,
                        verbose_name="Заголовок «Образование» (RU)",
                    ),
                ),
                (
                    "edu_title_en",
                    models.CharField(
                        blank=True,
                        default="Education",
                        max_length=60,
                        verbose_name="Заголовок «Образование» (EN)",
                    ),
                ),
                (
                    "lang_title_ru",
                    models.CharField(
                        blank=True,
                        default="Языки",
                        max_length=60,
                        verbose_name="Заголовок «Языки» (RU)",
                    ),
                ),
                (
                    "lang_title_en",
                    models.CharField(
                        blank=True,
                        default="Languages",
                        max_length=60,
                        verbose_name="Заголовок «Языки» (EN)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Если активных несколько — берётся последнее изменённое.",
                        verbose_name="Показывать на сайте",
                    ),
                ),
            ],
            options={
                "verbose_name": "Резюме",
                "verbose_name_plural": "Резюме",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "label_ru",
                    models.CharField(max_length=60, verbose_name="Подпись (RU)"),
                ),
                (
                    "label_en",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Подпись (EN)"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Что видно на сайте: @ник, почта, номер.",
                        max_length=200,
                        verbose_name="Значение",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="https://…, mailto:…, tel:…",
                        max_length=300,
                        verbose_name="Ссылка",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="Backend.resume",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResumeEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                ("year", models.CharField(max_length=20, verbose_name="Год")),
                (
                    "place",
                    models.CharField(
                        max_length=200, verbose_name="Учебное заведение / курс"
                    ),
                ),
                (
                    "detail_ru",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Описание (RU)"
                    ),
                ),
                (
                    "detail_en",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Описание (EN)"
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="Backend.resume",
                    ),
                ),
            ],
            options={
                "verbose_name": "Образование",
                "verbose_name_plural": "Образование",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResumeExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "period_ru",
                    models.CharField(
                        help_text="Например: Июнь 2026 — Август 2026",
                        max_length=80,
                        verbose_name="Период (RU)",
                    ),
                ),
                (
                    "period_en",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Период (EN)"
                    ),
                ),
                ("company", models.CharField(max_length=120, verbose_name="Компания")),
                (
                    "place_ru",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Город (RU)"
                    ),
                ),
                (
                    "place_en",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Город (EN)"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=200, verbose_name="Должность (RU)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Должность (EN)"
                    ),
                ),
                (
                    "points_ru",
                    models.TextField(
                        blank=True,
                        help_text="Каждый пункт — с новой строки.",
                        verbose_name="Задачи (RU)",
                    ),
                ),
                ("points_en", models.TextField(blank=True, verbose_name="Задачи (EN)")),
                (
                    "stack",
                    models.CharField(
                        blank=True,
                        help_text="Например: Python · Django · React",
                        max_length=300,
                        verbose_name="Стек",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience",
                        to="Backend.resume",
                    ),
                ),
            ],
            options={
                "verbose_name": "Место работы",
                "verbose_name_plural": "Опыт работы",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResumeFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "num",
                    models.CharField(
                        help_text="Например: 1.5, 5+, 3",
                        max_length=20,
                        verbose_name="Цифра",
                    ),
                ),
                (
                    "label_ru",
                    models.CharField(max_length=80, verbose_name="Подпись (RU)"),
                ),
                (
                    "label_en",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Подпись (EN)"
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="Backend.resume",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цифра «коротко»",
                "verbose_name_plural": "Цифры «коротко»",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResumeLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                ("name_ru", models.CharField(max_length=60, verbose_name="Язык (RU)")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Язык (EN)"
                    ),
                ),
                (
                    "level_ru",
                    models.CharField(max_length=40, verbose_name="Уровень (RU)"),
                ),
                (
                    "level_en",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Уровень (EN)"
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="Backend.resume",
                    ),
                ),
            ],
            options={
                "verbose_name": "Язык",
                "verbose_name_plural": "Языки",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResumeProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Название")),
                (
                    "kind_ru",
                    models.CharField(
                        blank=True,
                        help_text="Например: Unity 2D · WebGL",
                        max_length=80,
                        verbose_name="Ярлык (RU)",
                    ),
                ),
                (
                    "kind_en",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Ярлык (EN)"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, verbose_name="Описание (RU)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Описание (EN)"),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="Backend.resume",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResumeProjectLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "label_ru",
                    models.CharField(max_length=60, verbose_name="Текст кнопки (RU)"),
                ),
                (
                    "label_en",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Текст кнопки (EN)"
                    ),
                ),
                ("url", models.URLField(max_length=300, verbose_name="Ссылка")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="Backend.resumeproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка проекта",
                "verbose_name_plural": "Ссылки проекта",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResumeSkillGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=80, verbose_name="Группа (RU)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Группа (EN)"
                    ),
                ),
                (
                    "items",
                    models.TextField(
                        help_text="Через запятую: Python, Django, DRF",
                        verbose_name="Технологии",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_groups",
                        to="Backend.resume",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа навыков",
                "verbose_name_plural": "Технический стек",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
    ]
