# Generated by Django 6.0.6 on 2026-08-13 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0003_resume"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeHero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "show_badge",
                    models.BooleanField(default=True, verbose_name="Показывать ярлык"),
                ),
                (
                    "badge_ru",
                    models.CharField(
                        blank=True,
                        default="⚠ Только жёсткие игры",
                        max_length=120,
                        verbose_name="Ярлык (RU)",
                    ),
                ),
                (
                    "badge_en",
                    models.CharField(
                        blank=True,
                        default="⚠ Hardcore games only",
                        max_length=120,
                        verbose_name="Ярлык (EN)",
                    ),
                ),
                (
                    "title_ru",
                    models.TextField(
                        blank=True,
                        default="Без\nпощады.",
                        help_text="Каждая строка — с новой строки. Последняя, красная строка — в поле ниже.",
                        verbose_name="Заголовок (RU)",
                    ),
                ),
                (
                    "title_en",
                    models.TextField(
                        blank=True, default="No\nmercy.", verbose_name="Заголовок (EN)"
                    ),
                ),
                (
                    "title_accent_ru",
                    models.CharField(
                        blank=True,
                        default="Только игры.",
                        max_length=120,
                        verbose_name="Красная строка заголовка (RU)",
                    ),
                ),
                (
                    "title_accent_en",
                    models.CharField(
                        blank=True,
                        default="Just games.",
                        max_length=120,
                        verbose_name="Красная строка заголовка (EN)",
                    ),
                ),
                (
                    "show_deck",
                    models.BooleanField(
                        default=True, verbose_name="Показывать описание"
                    ),
                ),
                ("deck_ru", models.TextField(blank=True, verbose_name="Описание (RU)")),
                ("deck_en", models.TextField(blank=True, verbose_name="Описание (EN)")),
                (
                    "show_btn1",
                    models.BooleanField(
                        default=True, verbose_name="Показывать кнопку 1"
                    ),
                ),
                (
                    "btn1_text_ru",
                    models.CharField(
                        blank=True,
                        default="Открыть каталог →",
                        max_length=80,
                        verbose_name="Кнопка 1: текст (RU)",
                    ),
                ),
                (
                    "btn1_text_en",
                    models.CharField(
                        blank=True,
                        default="Open catalog →",
                        max_length=80,
                        verbose_name="Кнопка 1: текст (EN)",
                    ),
                ),
                (
                    "btn1_url",
                    models.CharField(
                        blank=True,
                        default="/games",
                        max_length=300,
                        verbose_name="Кнопка 1: ссылка",
                    ),
                ),
                (
                    "show_btn2",
                    models.BooleanField(
                        default=True, verbose_name="Показывать кнопку 2"
                    ),
                ),
                (
                    "btn2_text_ru",
                    models.CharField(
                        blank=True,
                        default="Читать новости",
                        max_length=80,
                        verbose_name="Кнопка 2: текст (RU)",
                    ),
                ),
                (
                    "btn2_text_en",
                    models.CharField(
                        blank=True,
                        default="Read the news",
                        max_length=80,
                        verbose_name="Кнопка 2: текст (EN)",
                    ),
                ),
                (
                    "btn2_url",
                    models.CharField(
                        blank=True,
                        default="/news",
                        max_length=300,
                        verbose_name="Кнопка 2: ссылка",
                    ),
                ),
                (
                    "show_stats",
                    models.BooleanField(default=True, verbose_name="Показывать цифры"),
                ),
                (
                    "show_art",
                    models.BooleanField(
                        default=True,
                        help_text="Если снять галочку — текст займёт всю ширину экрана.",
                        verbose_name="Показывать блок справа",
                    ),
                ),
                (
                    "art_image",
                    models.ImageField(
                        blank=True,
                        help_text="Если не загружать — останется фирменный узор с названием.",
                        null=True,
                        upload_to="hero/",
                        verbose_name="Картинка / логотип",
                    ),
                ),
                (
                    "art_title_ru",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Подпись на картинке (RU)",
                    ),
                ),
                (
                    "art_title_en",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Подпись на картинке (EN)",
                    ),
                ),
                (
                    "art_url",
                    models.CharField(
                        blank=True,
                        help_text="Куда ведёт клик по блоку. Пусто — блок не кликабельный.",
                        max_length=300,
                        verbose_name="Ссылка с картинки",
                    ),
                ),
                (
                    "show_score",
                    models.BooleanField(default=True, verbose_name="Показывать оценку"),
                ),
                (
                    "score",
                    models.CharField(
                        blank=True, default="9.4", max_length=10, verbose_name="Оценка"
                    ),
                ),
                (
                    "score_label_ru",
                    models.CharField(
                        blank=True,
                        default="из 10",
                        max_length=40,
                        verbose_name="Подпись к оценке (RU)",
                    ),
                ),
                (
                    "score_label_en",
                    models.CharField(
                        blank=True,
                        default="out of 10",
                        max_length=40,
                        verbose_name="Подпись к оценке (EN)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Если активных несколько — берётся последний изменённый.",
                        verbose_name="Показывать на сайте",
                    ),
                ),
            ],
            options={
                "verbose_name": "Главная: первый экран",
                "verbose_name_plural": "Главная: первый экран",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="HeroStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                ("num", models.CharField(max_length=20, verbose_name="Цифра")),
                (
                    "label_ru",
                    models.CharField(max_length=80, verbose_name="Подпись (RU)"),
                ),
                (
                    "label_en",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Подпись (EN)"
                    ),
                ),
                (
                    "hero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="Backend.homehero",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цифра",
                "verbose_name_plural": "Цифры",
                "ordering": ["order", "id"],
            },
        ),
    ]
