# Generated by Django 6.0.6 on 2026-08-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0004_home_hero"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gameplatformrelease",
            options={
                "verbose_name": "Платформа продукта",
                "verbose_name_plural": "Платформы продукта",
            },
        ),
        migrations.AlterModelOptions(
            name="games",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.AlterModelOptions(
            name="platform",
            options={"verbose_name": "Платформа", "verbose_name_plural": "Платформы"},
        ),
        migrations.AddField(
            model_name="games",
            name="kind",
            field=models.CharField(
                choices=[
                    ("game", "Игра"),
                    ("desktop", "Десктопная программа"),
                    ("web", "Веб-приложение"),
                    ("mobile", "Мобильное приложение"),
                    ("other", "Другое"),
                ],
                default="game",
                help_text="Показывается плашкой на карточке и даёт фильтр в каталоге.",
                max_length=20,
                verbose_name="Тип продукта",
            ),
        ),
        migrations.AddField(
            model_name="platform",
            name="icon",
            field=models.CharField(
                choices=[
                    ("windows", "Windows"),
                    ("linux", "Linux"),
                    ("macos", "macOS"),
                    ("web", "Веб / браузер"),
                    ("android", "Android"),
                    ("ios", "iOS"),
                    ("playstation", "PlayStation"),
                    ("xbox", "Xbox"),
                    ("nintendo", "Nintendo"),
                    ("steam", "Steam"),
                    ("itch", "itch.io"),
                    ("other", "Без значка"),
                ],
                default="other",
                help_text="Какой значок рисовать на карточке продукта.",
                max_length=20,
                verbose_name="Значок",
            ),
        ),
        migrations.AlterField(
            model_name="gameplatformrelease",
            name="release_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата выхода"),
        ),
        migrations.AlterField(
            model_name="gameplatformrelease",
            name="status",
            field=models.CharField(
                choices=[
                    ("released", "Вышло"),
                    ("waiting", "Скоро"),
                    ("not_released", "Не выпущено"),
                ],
                default="not_released",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="gameplatformrelease",
            name="url_platform",
            field=models.URLField(blank=True, verbose_name="Ссылка на скачивание"),
        ),
        migrations.AlterField(
            model_name="games",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="games",
            name="image",
            field=models.ImageField(upload_to="images/", verbose_name="Обложка"),
        ),
        migrations.AlterField(
            model_name="games",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="games",
            name="url",
            field=models.URLField(blank=True, verbose_name="Основная ссылка"),
        ),
        migrations.AlterField(
            model_name="platform",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="Своя картинка"
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
    ]
