# Generated by Django 6.0.6 on 2026-08-16 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_product_kind_and_platform_icons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='vlogs',
            options={'ordering': ['-created_at'], 'verbose_name': 'Влог', 'verbose_name_plural': 'Влоги'},
        ),
        migrations.AlterField(
            model_name='games',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='games',
            name='image',
            field=models.ImageField(blank=True, help_text='Не обязательно. Без обложки карточка покажет узор с первой буквой названия.', null=True, upload_to='images/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='games',
            name='url',
            field=models.URLField(blank=True, default='', verbose_name='Основная ссылка'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='news',
            name='media',
            field=models.FileField(blank=True, help_text='Не обязательно. Без файла карточка покажет узор с первой буквой заголовка.', null=True, upload_to='news/', verbose_name='Картинка или видео'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, help_text='Можно не заполнять — соберётся из заголовка.', max_length=255, unique=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=230, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(blank=True, default='', max_length=230, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='vlogs',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='vlogs',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='vlogs',
            name='media',
            field=models.FileField(blank=True, help_text='Не обязательно. Без файла карточка покажет узор с первой буквой заголовка.', null=True, upload_to='vlogs/', verbose_name='Картинка или видеофайл'),
        ),
        migrations.AlterField(
            model_name='vlogs',
            name='slug',
            field=models.SlugField(blank=True, help_text='Можно не заполнять — соберётся из заголовка.', max_length=255, unique=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='vlogs',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vlogs',
            name='url',
            field=models.URLField(blank=True, default='', help_text='YouTube и Vimeo встраиваются плеером, остальные — кнопкой «смотреть».', max_length=230, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='vlogs',
            name='vlog_title',
            field=models.CharField(max_length=500, verbose_name='Заголовок'),
        ),
    ]
