# Generated by Django 6.0.6 on 2026-08-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_alter_news_options_alter_vlogs_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplatformrelease',
            name='status',
            field=models.CharField(choices=[('not_released', 'Не выпущено'), ('in_dev', 'В разработке'), ('beta', 'Бета'), ('waiting', 'Скоро'), ('released', 'Вышло')], default='not_released', max_length=20, verbose_name='Статус'),
        ),
    ]
