# Generated by Django 6.0.6 on 2026-08-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_alter_gameplatformrelease_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='description_en',
            field=models.TextField(blank=True, default='', help_text='Не обязательно. Если пусто — на английской версии покажется русский текст.', verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='games',
            name='title_en',
            field=models.CharField(blank=True, default='', help_text='Не обязательно. Если пусто — на английской версии покажется русский текст.', max_length=100, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(blank=True, default='', help_text='Не обязательно. Если пусто — на английской версии покажется русский текст.', verbose_name='Текст (EN)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, default='', help_text='Не обязательно. Если пусто — на английской версии покажется русский текст.', max_length=230, verbose_name='Заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='vlogs',
            name='text_en',
            field=models.TextField(blank=True, default='', help_text='Не обязательно. Если пусто — на английской версии покажется русский текст.', verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='vlogs',
            name='vlog_title_en',
            field=models.CharField(blank=True, default='', help_text='Не обязательно. Если пусто — на английской версии покажется русский текст.', max_length=500, verbose_name='Заголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='games',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание (RU)'),
        ),
        migrations.AlterField(
            model_name='games',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название (RU)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Текст (RU)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=230, verbose_name='Заголовок (RU)'),
        ),
        migrations.AlterField(
            model_name='vlogs',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Описание (RU)'),
        ),
        migrations.AlterField(
            model_name='vlogs',
            name='vlog_title',
            field=models.CharField(max_length=500, verbose_name='Заголовок (RU)'),
        ),
    ]
