# Generated by Django 6.0.6 on 2026-08-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_games_description_en_games_title_en_news_content_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='kind',
            field=models.CharField(choices=[('devlog', 'Девлог'), ('release', 'Релиз'), ('update', 'Обновление'), ('announce', 'Анонс'), ('other', 'Разное')], default='devlog', help_text='Показывается плашкой на карточке и даёт фильтр в списке новостей.', max_length=20, verbose_name='Раздел'),
        ),
        migrations.AddField(
            model_name='vlogs',
            name='kind',
            field=models.CharField(choices=[('devlog', 'Девлог'), ('tutorial', 'Туториал'), ('review', 'Обзор'), ('stream', 'Стрим'), ('other', 'Разное')], default='devlog', help_text='Показывается плашкой на карточке и даёт фильтр в списке влогов.', max_length=20, verbose_name='Раздел'),
        ),
    ]
